name: godfident
description: Personal Bible Study & Spiritual Growth App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # HTTP
  dio: ^5.4.3

  # Routing
  go_router: ^14.2.0

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.1

  # UI
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Markdown
  flutter_markdown: ^0.7.3

  # Charts
  fl_chart: ^0.68.0

  # Calendar / Heatmap
  syncfusion_flutter_datepicker: ^24.2.9
  flutter_calendar_carousel: ^2.4.2

# Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  collection: ^1.18.0
  url_launcher: ^6.2.6

  # Local notifications & alarms
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  android_alarm_manager_plus: ^4.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

